[package]
name = "ts_query_ls"
version = "1.2.4"
authors = ["Riley Bruins <ribru17@gmail.com>"]
edition = "2021"
description = "An LSP implementation for Tree-sitter's query files"
license = "MIT"
repository = "https://github.com/ribru17/ts_query_ls"

[dependencies]
dashmap = "6.1.0"
dissimilar = "1.0.9"
env_logger = "0.11.5"
lazy_static = "1.5.0"
libloading = "0.8.5"
log = "0.4.22"
regex = "1.11.0"
ropey = "1.6.1"
serde = "1.0.210"
serde_json = "1.0.132"
streaming-iterator = "0.1.9"
tokio = { version = "1.40.0", features = ["rt-multi-thread", "macros", "io-std"] }
tower-lsp = "0.20.0"
tracing-subscriber = "0.3.18"
tree-sitter = { version = "0.24.4", features = ["std", "wasm"] }
tree-sitter-query = { git = "https://github.com/tree-sitter-grammars/tree-sitter-query", rev = "d0d9126a9b80a0bb609acdf960d3f1613fc319db", version = "0.4.0" }

[build-dependencies]
cc = "1.1.30"
